services:
  db: 
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=admindb
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - "3306:3306"
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
  www:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
      - 443:443
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=localhost
      - PMA_PORT=3306
